apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: interconnect
spec:
  selector:
    app: interconnect-server
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort