apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: interconnect
data:
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "interconnect"
  MONGODB_DATABASE_URI: "mongodb://mongo:27017/interconnect"
  
  NODE_ENV: "production"
  PORT: "5000"
  REACT_APP_API_URL: "http://localhost:30500"