apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: interconnect
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: interconnect-client
  template:
    metadata:
      labels:
        app: interconnect-client
    spec:
      containers:
        - name: interconnect-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: REACT_APP_API_URL
              value: {{ .Values.env.REACT_APP_API_URL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}