apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: interconnect
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: interconnect-server
  template:
    metadata:
      labels:
        app: interconnect-server
    spec:
      containers:
        - name: interconnect-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: NODE_ENV
            - name: MONGODB_DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: MONGODB_DATABASE_URI
          resources:
            {{- toYaml .Values.resources | nindent 12 }}