apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: interconnect
spec:
  selector:
    app: interconnect-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}