apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: interconnect
spec:
  selector:
    app: interconnect-client
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
